server:
  port: 11451

spring:
  application:
    name: yuni-application
  datasource:  # 数据库配置，如果非专业开发者，不建议修改
    url: jdbc:sqlite:./${bot.app.sqlite-db-file}  # 数据库使用 sqlite, 数据库文件默认在跟目录下。文件名由下方的 sqlite-db-file 属性指定
    driver-class-name: org.sqlite.JDBC  # 数据库驱动
    username:
    password:
  data:
    redis:
      # 服务器地址
      # 端口号
      port: 6379
      # 密码（无密码则注释或留空）
      password:
      # 数据库索引（默认0，Redis支持16个数据库）
      database: 0
      # 连接超时时间
      timeout: 10000ms
      # 连接池配置（基于commons-pool2）
      lettuce:
        pool:
          # 最大活跃连接数
          max-active: 8
          # 最大空闲连接数
          max-idle: 8
          # 最小空闲连接数
          min-idle: 0
          # 最大等待时间（-1表示无限制）
          max-wait: -1ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: auto

logging:
  config: classpath:log4j2.yml  # 日志配置文件，详见其中内容

onebot:
  communication:
    mode: http  # 与 OneBot 的通信方式，目前只实现了 http
    token:
  api:
    url: http://127.0.0.1:3000/  # OneBot 客户端 API 的 base url

bot:
  qq: 123456789  # 机器人的 QQ 号
  nickname: xcw  # 机器人的昵称
  master-qq: 987654321  # 你自己的 QQ 号
  app:
    command-flag: /  # 定义命令时的全局前缀
    plugin:
      directory: yuni-application/plugins  # 插件 jar 包的位置，默认位于 application 模块的 plugins 目录下
    sqlite-db-file: yuni3.db  # 应用使用的 sqlite 数据库文件名，该文件位于根目录下

yuni:  # 用于 banner.txt
  name: Yuni
  version: v3.0.0
  description: 基于 Spring Boot 开发的一款聊天机器人